User can specify cluster ID to join or create new cluster, and kube-down will remove quitted apiserver endpoint.

diff --git a/kube-down b/kube-down
--- a/kube-down
+++ b/kube-down
@@ -1,37 +1,98 @@
 #!/bin/bash
 set -e
 
-function stop_k8s(){
-  local IPADDR="$1"
-  local ETCD_CLIENT_PORT="$2"
-  local K8S_VERSION="$3"
-  local K8S_PORT="$4"
-  local REGISTRY="$5"
+function remove_node_from_endpoints(){
+  local HYPERKUBE_IMAGE="$1"
+  local APISERVER="$2"
+  local IPMASK_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,2\}"
+  local GW_IFACE="$(ip route | grep default | awk '{print $5}')"
+  local IPADDR="$(ip addr show dev "${GW_IFACE}" | grep -o "${IPMASK_PATTERN}" | cut -d '/' -f 1)"
 
-  # Find an API server
-  local APISERVER=""
-  if curl --insecure -u admin:admin -sf "https://127.0.0.1:${K8S_PORT}" &>/dev/null; then
-    APISERVER="127.0.0.1:${K8S_PORT}"
+  local NEW_ENDPOINTS="$(docker run \
+    --net=host \
+    --rm=true \
+    "${HYPERKUBE_IMAGE}" \
+    /hyperkube kubectl -s "${APISERVER}" \
+    --insecure-skip-tls-verify \
+    --username="admin" \
+    --password="admin" \
+    get ep kubernetes --namespace=default -o json \
+      | jq ".subsets[].addresses[] | select(.ip != \"${IPADDR}\")" \
+      | jq -s -c .)"
+
+  [[ "${NEW_ENDPOINTS}" == "[]" ]] && return 0
+
+  local NEW_PATCH="{\"subsets\":[{\"addresses\":${NEW_ENDPOINTS},\"ports\":[{\"name\":\"https\",\"port\":6443,\"protocol\":\"TCP\"}]}]}"
+
+  docker run \
+    --net=host \
+    --rm=true \
+    "${HYPERKUBE_IMAGE}" \
+    /hyperkube kubectl -s "${APISERVER}" \
+    --insecure-skip-tls-verify \
+    --username="admin" \
+    --password="admin" \
+    patch ep kubernetes \
+    --type='merge' \
+    -p "${NEW_PATCH}"
+}
+
+function get_endpoint_amount(){
+  local ETCD_CLIENT_PORT="$1"
+  local NODE_LIST="$(curl -m 2 -sf "127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/services/endpoints/default/kubernetes" \
+                     | jq -r '.node.value' \
+                     | jq -r '.subsets[].addresses[].ip')"
+  [[ -z "${NODE_LIST}" ]] && { echo "Could not connect to etcd server!" 1>&2; return 1; }
+  [[ "${NODE_LIST}" == "null" ]] && { echo "No such any endpoint!" 1>&2; return 1; }
+
+  local ENDPOINT_AMOUNT="$(echo "${NODE_LIST}" | wc -l)"
+  echo "${ENDPOINT_AMOUNT}"
+}
+
+# Find an API server
+function find_an_apiserver(){
+  local ETCD_CLIENT_PORT="$1"
+  local K8S_PORT="$2"
+  local K8S_INSECURE_PORT="$3"
+  local APISERVER
+  local NODE
+
+  if curl --insecure -u admin:admin -m 2 -sf "http://127.0.0.1:${K8S_INSECURE_PORT}" &>/dev/null; then
+    APISERVER="http://127.0.0.1:${K8S_INSECURE_PORT}"
   else
     # If API server is not running on local, searching it from other nodes.
-    local NODE_LIST="$(curl -sf 127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/minions \
-                      | jq -r .node.nodes[].key \
-                      | sed -n "s/.*\/\(.*\)$/\1/p")"
-    local NODE=""
+    local NODE_LIST="$(curl -m 2 -sf "127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/services/endpoints/default/kubernetes" \
+                       | jq -r '.node.value' \
+                       | jq -r '.subsets[].addresses[].ip')"
+    [[ -z "${NODE_LIST}" ]] && { echo "Could not connect to etcd server!" 1>&2; return 1; }
+
     for NODE in ${NODE_LIST}; do
-      if curl --insecure -u admin:admin -sf "https://${NODE}:${K8S_PORT}" &>/dev/null; then
-        APISERVER="${NODE}:${K8S_PORT}"
+      if curl --insecure -u admin:admin -m 2 -sf "https://${NODE}:${K8S_PORT}" &>/dev/null; then
+        APISERVER="https://${NODE}:${K8S_PORT}"
         break
       fi
     done
   fi
+  [[ -z "${APISERVER}" ]] && { echo "Could not find any apiserver!" 1>&2; return 1; }
+
+  echo "${APISERVER}"
+}
+
+function stop_k8s(){
+  local IPADDR="$1"
+  local ETCD_CLIENT_PORT="$2"
+  local HYPERKUBE_IMAGE="$3"
+  local APISERVER="$4"
 
   # Drain node in preparation for maintenance.
   docker run \
     --net=host \
     --rm=true \
-    "${REGISTRY}/hyperkube-amd64:v${K8S_VERSION}" \
-    /hyperkube kubectl \
+    "${HYPERKUBE_IMAGE}" \
+    /hyperkube kubectl -s "${APISERVER}" \
+    --insecure-skip-tls-verify \
+    --username="admin" \
+    --password="admin" \
     drain "${IPADDR}" --force --ignore-daemonsets --delete-local-data
 
   if [[ "${EXIT}" == "true" ]]; then
@@ -39,8 +100,11 @@ function stop_k8s(){
     docker run \
       --net=host \
       --rm=true \
-      "${REGISTRY}/hyperkube-amd64:v${K8S_VERSION}" \
-      /hyperkube kubectl \
+      "${HYPERKUBE_IMAGE}" \
+      /hyperkube kubectl -s "${APISERVER}" \
+      --insecure-skip-tls-verify \
+      --username="admin" \
+      --password="admin" \
       delete node "${IPADDR}"
   fi
 
@@ -49,7 +113,7 @@ function stop_k8s(){
   echo '{}' | tee /etc/kubernetes/manifests-multi/addon-manager-multinode.json &>/dev/null
 
   echo -n "Waiting for all k8s pods stopped ..." 1>&2
-  until [[ "$(docker ps | grep ${REGISTRY}/hyperkube | wc -l)" -le "2" ]]; do
+  until [[ "$(docker ps | grep "${HYPERKUBE_IMAGE}" | wc -l)" -le "2" ]]; do
     echo -n "." 1>&2
     sleep 1
   done
@@ -87,6 +151,7 @@ Options:
 -f, --force                              Force to kill named k8sup containers
     --exit-local-etcd-only               Exit the local etcd member from cluster
     --exit-remote-etcd=REMOTE_IPADDR     Exit the remote etcd member from cluster
+    --debug                              Enable debug mode
 -h, --help                               This help text
 "
 
@@ -96,7 +161,7 @@ Options:
 function get_options(){
   local PROGNAME="${0##*/}"
   local SHORTOPTS="rfh"
-  local LONGOPTS="remove,stop-k8s-only,force,exit-local-etcd-only,exit-remote-etcd:,help"
+  local LONGOPTS="remove,stop-k8s-only,force,exit-local-etcd-only,exit-remote-etcd:,debug,help"
   local PARSED_OPTIONS=""
 
   PARSED_OPTIONS="$(getopt -o "${SHORTOPTS}" --long "${LONGOPTS}" -n "${PROGNAME}" -- "$@")" || exit 1
@@ -125,6 +190,11 @@ function get_options(){
               export EX_REMOTE_ETCD="true"
               export EX_REMOTE_IPADDR="$2"
               shift 2
+              ;;
+             --debug)
+              set -x
+              export SHELLOPTS
+              shift
               ;;
           -h|--help)
               show_usage
@@ -158,7 +228,9 @@ function main(){
   local ETCD_CLIENT_PORT="${EX_ETCD_CLIENT_PORT}"
   local K8S_VERSION="${EX_K8S_VERSION}"
   local K8S_PORT="${EX_K8S_PORT}"
+  local K8S_INSECURE_PORT="${EX_K8S_INSECURE_PORT}"
   local REGISTRY="${EX_REGISTRY}"
+  local HYPERKUBE_IMAGE="${EX_HYPERKUBE_IMAGE}"
   local LOCAL_ETCD="true"
 
   local STOP_K8S_ONLY="${EX_STOP_K8S_ONLY}"
@@ -167,10 +239,8 @@ function main(){
   local REMOTE_ETCD="${EX_REMOTE_ETCD}"
   local REMOTE_IPADDR="${EX_REMOTE_IPADDR}"
   local FORCE="${EX_FORCE}"
-  if [[ "${STOP_K8S_ONLY}" == "true" ]]; then
-    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${K8S_VERSION}" "${K8S_PORT}" "${REGISTRY}"
-    exit 0
-  fi
+  local APISERVER
+  local ENDPOINT_AMOUNT
   if [[ "${LOCAL_ETCD_ONLY}" == "true" ]]; then
     exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
     exit 0
@@ -189,8 +259,18 @@ function main(){
     fi
   else
     # Default removing
+    APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}")" || exit 1
     echo "Stopping k8s containers..." 1>&2
-    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${K8S_VERSION}" "${K8S_PORT}" "${REGISTRY}"
+    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${HYPERKUBE_IMAGE}" "${APISERVER}"
+    ENDPOINT_AMOUNT="$(get_endpoint_amount "${ETCD_CLIENT_PORT}")" || exit 1
+    if [[ "${ENDPOINT_AMOUNT}" -gt "1" ]]; then
+      # Try to find another apiserver for removing this node from endpoints
+      APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}")"
+       && remove_node_from_endpoints "${HYPERKUBE_IMAGE}" "${APISERVER}" || true
+    fi
+    if [[ "${STOP_K8S_ONLY}" == "true" ]]; then
+      exit 0
+    fi
     if [[ "${EXIT}" == "true" ]]; then
       exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
     fi
