Support '--restart' for restarting k8sup.

diff --git a/kube-down b/kube-down
--- a/kube-down
+++ b/kube-down
@@ -2,14 +2,21 @@
 set -e
 
 function remove_node_from_endpoints(){
-  local IPMASK_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,2\}"
   local IPPORT_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{1,5\}"
+  local IPMASK_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,2\}"
+  local GW_IFACE="$(ip route | grep default | awk '{print $5}')"
+  local IPADDR=$(ip addr show dev "${GW_IFACE}" | grep -o "${IPMASK_PATTERN}" | cut -d '/' -f 1)
   local HYPERKUBE_IMAGE="$1"
   local APIHOST="$(echo "$2" | grep -o "${IPPORT_PATTERN}")"
   local KUBELET_VARLIB="$3"
-  local GW_IFACE="$(ip route | grep default | awk '{print $5}')"
-  local IPADDR="$(ip addr show dev "${GW_IFACE}" | grep -o "${IPMASK_PATTERN}" | cut -d '/' -f 1)"
+  local REMOTE_K8S_IPADDR="$4"
   local APISERVER=""
+
+  if [[ -n "${REMOTE_K8S_IPADDR}" ]]; then
+    IPADDR="$(curl -sf "http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/k8sup/cluster/default-iface-ipaddr/${REMOTE_K8S_IPADDR}" \
+              | jq -r '.node.value')"
+    [[ -z "${IPADDR}" ]] && { echo "Could not get the default interface IP address of remote node." 1>&2 && return 1; }
+  fi
 
   if [[ "${APIHOST}" == "127.0.0.1"* ]]; then
     APISERVER="http://${APIHOST}"
@@ -97,7 +104,6 @@ function find_an_apiserver(){
   echo "${APISERVER}"
 }
 
-# TODO: Exit remote k8s node
 function stop_k8s(){
   local IPPORT_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{1,5\}"
   local IPADDR="$1"
@@ -105,32 +111,43 @@ function stop_k8s(){
   local KUBELET_VARLIB="$3"
   local HYPERKUBE_IMAGE="$4"
   local APIHOST="$(echo "$5" | grep -o "${IPPORT_PATTERN}")"
+  local REMOTE_K8S_IPADDR="$6"
+  local EXIT="$7"
   local CONTAINER_IDS=""
   local APISERVER=""
 
+  # Only for exit remote k8s service
+  if [[ -n "${REMOTE_K8S_IPADDR}" ]]; then
+    IPADDR="${REMOTE_K8S_IPADDR}"
+    EXIT="true"
+  fi
   if [[ "${APIHOST}" == "127.0.0.1"* ]]; then
     APISERVER="http://${APIHOST}"
-  elif [[ -n "${APIHOST}" ]]; then
+  elif [[ -n "${APIHOST}" ]] && [[ -z "${REMOTE_K8S_IPADDR}" ]]; then
+    # Only for exit local k8s service
     iptables -w -t nat -I OUTPUT --dest 10.0.0.1 -p tcp --dport 443 -j DNAT --to-dest "${APIHOST}"
     APISERVER="https://10.0.0.1:443"
   else
     return 1
   fi
 
-  # Drain node in preparation for maintenance.
-  until \
-      docker run \
-        --net=host \
-        --rm=true \
-        --volume=${KUBELET_VARLIB}/kubeconfig:${KUBELET_VARLIB}/kubeconfig:ro \
-        "${HYPERKUBE_IMAGE}" \
-        /hyperkube kubectl -s "${APISERVER}" \
-          --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
-          drain "${IPADDR}" --force --ignore-daemonsets --delete-local-data 2>/dev/null; do
-    sleep 1
-  done
-
   if [[ "${EXIT}" == "true" ]]; then
+    # Drain node in preparation for maintenance.
+    local MSG
+    until \
+        MSG="(docker run \
+          --net=host \
+          --rm=true \
+          --volume=${KUBELET_VARLIB}/kubeconfig:${KUBELET_VARLIB}/kubeconfig:ro \
+          "${HYPERKUBE_IMAGE}" \
+          /hyperkube kubectl -s "${APISERVER}" \
+            --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
+            drain "${IPADDR}" --force --ignore-daemonsets --delete-local-data 2>&1)"; do
+      [[ "$(echo "${MSG}" | grep "nodes .* not found")" ]] && return 1
+      echo "Try again..." 1>&2
+      sleep 1
+    done
+
     # Exit k8s cluster
     docker run \
       --net=host \
@@ -140,41 +157,52 @@ function stop_k8s(){
       /hyperkube kubectl -s "${APISERVER}" \
         --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
         delete node "${IPADDR}"
+  else
+    local EXCLUDE_POD_CMD="| grep -v 'k8s_POD\.' | grep -v -E '[[:alnum:]]{8}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{12}'"
   fi
 
-  # Remove k8s system pods conf
-  echo '{}' | tee /etc/kubernetes/manifests-multi/master-multi.json &>/dev/null
-  echo '{}' | tee /etc/kubernetes/manifests-multi/addon-manager-multinode.json &>/dev/null
+  # Only for exit local k8s service
+  if [[ -z "${REMOTE_K8S_IPADDR}" ]]; then
+    # Remove k8s system pods conf
+    echo '{}' | tee /etc/kubernetes/manifests-multi/master-multi.json &>/dev/null
+    echo '{}' | tee /etc/kubernetes/manifests-multi/addon-manager-multinode.json &>/dev/null
 
-  docker stop k8sup-kubelet 1>/dev/null || true
-  CONTAINER_IDS="$(docker ps -a | grep -E "k8s_.*(kube-addon-manager-|setup).*_kube-system" | awk '{print $1}')"
-  [[ -n "${CONTAINER_IDS}" ]] && docker kill ${CONTAINER_IDS} 1>/dev/null || true
-  CONTAINER_IDS="$(docker ps -a | grep -E "k8s_([[:alnum:]]|-)+\.[[:alnum:]]{7,8}_.*_kube-system" | awk '{print $1}')"
-  [[ -n "${CONTAINER_IDS}" ]] && docker stop ${CONTAINER_IDS} 1>/dev/null || true
-  CONTAINER_IDS="$(docker ps -a | grep -E "k8s_([[:alnum:]]|-)+\.[[:alnum:]]{7,8}_.*_kube-system" | awk '{print $1}')"
-  [[ -n "${CONTAINER_IDS}" ]] && docker rm -v ${CONTAINER_IDS} 1>/dev/null || true
-
-  echo -n "Waiting for all k8s pods stopped..." 1>&2
-  until [[ "$(docker ps | grep "${HYPERKUBE_IMAGE}" | wc -l)" -le "2" ]]; do
-    echo -n "." 1>&2
-    sleep 1
-  done
-  echo 1>&2
-
-  until ! docker ps | grep -w 'k8sup-kubelet'; do
     docker stop k8sup-kubelet 1>/dev/null || true
-    docker rm k8sup-kubelet 1>/dev/null || true
-  done
+    CONTAINER_IDS="$(docker ps | grep -E "k8s_.*(k8s-proxy).*_kube-system" | awk '{print $1}')"
+    [[ -n "${CONTAINER_IDS}" ]] && docker stop ${CONTAINER_IDS} 1>/dev/null || true
+    CONTAINER_IDS="$(docker ps ${EXCLUDE_POD_CMD} | grep -E "k8s_.*(kube-addon-manager-|setup).*_kube-system" | awk '{print $1}')"
+    [[ -n "${CONTAINER_IDS}" ]] && docker kill ${CONTAINER_IDS} 1>/dev/null || true
+    CONTAINER_IDS="$(docker ps ${EXCLUDE_POD_CMD} | grep -E "k8s_([[:alnum:]]|-)+\.[[:alnum:]]{7,8}_.*_kube-system" | awk '{print $1}')"
+    [[ -n "${CONTAINER_IDS}" ]] && docker stop ${CONTAINER_IDS} 1>/dev/null || true
+    CONTAINER_IDS="$(docker ps -a ${EXCLUDE_POD_CMD} | grep -E "k8s_([[:alnum:]]|-)+\.[[:alnum:]]{7,8}_.*_kube-system" | awk '{print $1}')"
+    [[ -n "${CONTAINER_IDS}" ]] && docker rm -v ${CONTAINER_IDS} 1>/dev/null || true
 
-  if [[ -n "$(iptables -w -S -t nat | grep 10.0.0.1/32 | grep "${APIHOST}")" ]]; then
-    iptables -w -t nat -D OUTPUT --dest 10.0.0.1 -p tcp --dport 443 -j DNAT --to-dest "${APIHOST}"
+    echo -n "Waiting for all k8s pods stopped..." 1>&2
+    until [[ "$(docker ps | grep "${HYPERKUBE_IMAGE}" | wc -l)" -le "2" ]]; do
+      echo -n "." 1>&2
+      sleep 1
+    done
+    echo 1>&2
+
+    until ! docker ps | grep -w 'k8sup-kubelet'; do
+      docker stop k8sup-kubelet 1>/dev/null || true
+      docker rm k8sup-kubelet 1>/dev/null || true
+    done
+
+    if [[ -n "$(iptables -w -S -t nat | grep 10.0.0.1/32 | grep "${APIHOST}")" ]]; then
+      iptables -w -t nat -D OUTPUT --dest 10.0.0.1 -p tcp --dport 443 -j DNAT --to-dest "${APIHOST}"
+    fi
+  else
+    echo "K8S node ${IPADDR} has been exited." 1>&2
   fi
 }
 
 function exit_etcd(){
   local IPADDR="$1"
   local ETCD_CLIENT_PORT="$2"
-  local LOCAL_ETCD="$3"
+  local REMOTE_ETCD_IPADDR="$3"
+
+  [[ -n "${REMOTE_ETCD_IPADDR}" ]] && IPADDR="${REMOTE_ETCD_IPADDR}"
 
   # Exit etcd cluster
   local MEMBER_LIST="$(curl -s http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members)"
@@ -182,12 +210,12 @@ function exit_etcd(){
     local MEMBER_ID="$(echo "${MEMBER_LIST}" | jq -r ".members[] | select(contains({clientURLs: [\"/${IPADDR}:\"]})) | .id")"
     test "${MEMBER_ID}" && curl -s "http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members/${MEMBER_ID}" -XDELETE
   fi
-  if [[ "${LOCAL_ETCD}" == "true" ]]; then
+  if [[ -n "${REMOTE_ETCD_IPADDR}" ]]; then
+    echo "etcd node ${IPADDR} has been exited." 1>&2
+  else
     docker stop k8sup-etcd 1>/dev/null
     docker rm k8sup-etcd 1>/dev/null
     rm -rf "/var/lib/etcd/"*
-  else
-    echo "Node ${IPADDR} has been exited." 1>&2
   fi
 }
 
@@ -199,6 +227,7 @@ Options:
 -f, --force                              Force to kill named k8sup containers
     --exit-local-etcd-only               Exit the local etcd member from cluster
     --exit-remote-etcd=REMOTE_IPADDR     Exit the remote etcd member from cluster
+    --exit-remote-k8s=REMOTE_IPADDR      Exit the remote k8s node from cluster
     --debug                              Enable debug mode
 -h, --help                               This help text
 "
@@ -209,8 +238,9 @@ Options:
 function get_options(){
   local PROGNAME="${0##*/}"
   local SHORTOPTS="rfh"
-  local LONGOPTS="remove,stop-k8s-only,force,exit-local-etcd-only,exit-remote-etcd:,debug,help"
+  local LONGOPTS="remove,stop-k8s-only,force,exit-local-etcd-only,exit-remote-etcd:,exit-remote-k8s:,debug,help"
   local PARSED_OPTIONS=""
+  local IPADDR_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
 
   PARSED_OPTIONS="$(getopt -o "${SHORTOPTS}" --long "${LONGOPTS}" -n "${PROGNAME}" -- "$@")" || exit 1
   eval set -- "${PARSED_OPTIONS}"
@@ -231,12 +261,15 @@ function get_options(){
               shift
               ;;
              --exit-local-etcd-only)
-              export EX_LOCAL_ETCD_ONLY="true"
+              export EX_EXIT_LOCAL_ETCD_ONLY="true"
               shift
               ;;
              --exit-remote-etcd)
-              export EX_REMOTE_ETCD="true"
-              export EX_REMOTE_IPADDR="$2"
+              export EX_REMOTE_ETCD_IPADDR="$2"
+              shift 2
+              ;;
+             --exit-remote-k8s)
+              export EX_REMOTE_K8S_IPADDR="$2"
               shift 2
               ;;
              --debug)
@@ -261,8 +294,14 @@ function get_options(){
       esac
   done
 
-  if [[ "${EX_REMOTE_ETCD}" == "true" ]] && [[ -z "${EX_REMOTE_IPADDR}" ]]; then
+  if [[ -n "${EX_REMOTE_ETCD_IPADDR}" ]] \
+   && [[ -z "$(echo "${EX_REMOTE_ETCD_IPADDR}" | grep -o "${IPADDR_PATTERN}")" ]]; then
     echo "Need IP address of remote etcd node, exiting..." 1>&2
+    exit 1
+  fi
+  if [[ -n "${EX_REMOTE_K8S_IPADDR}" ]] \
+   && [[ -z "$(echo "${EX_REMOTE_K8S_IPADDR}" | grep -o "${IPADDR_PATTERN}")" ]]; then
+    echo "Need IP address of remote k8s node, exiting..." 1>&2
     exit 1
   fi
 }
@@ -270,7 +309,6 @@ function get_options(){
 function main(){
   source "$(dirname "$0")/runcom"
   get_options "$@"
-  local EXIT="${EX_EXIT}"
 
   source "/root/.bashrc"
   local IPADDR="${EX_IPADDR}"
@@ -280,24 +318,28 @@ function main(){
   local K8S_INSECURE_PORT="${EX_K8S_INSECURE_PORT}"
   local REGISTRY="${EX_REGISTRY}"
   local HYPERKUBE_IMAGE="${EX_HYPERKUBE_IMAGE}"
-  local LOCAL_ETCD="true"
 
+  local EXIT="${EX_EXIT}"
   local STOP_K8S_ONLY="${EX_STOP_K8S_ONLY}"
-  local EXIT_ETCD_ONLY="${EX_EXIT_ETCD_ONLY}"
-  local LOCAL_ETCD_ONLY="${EX_LOCAL_ETCD_ONLY}"
-  local REMOTE_ETCD="${EX_REMOTE_ETCD}"
-  local REMOTE_IPADDR="${EX_REMOTE_IPADDR}"
+  local EXIT_LOCAL_ETCD_ONLY="${EX_EXIT_LOCAL_ETCD_ONLY}"
+  local REMOTE_ETCD_IPADDR="${EX_REMOTE_ETCD_IPADDR}"
+  local REMOTE_K8S_IPADDR="${EX_REMOTE_K8S_IPADDR}"
   local FORCE="${EX_FORCE}"
   local KUBELET_VARLIB="/var/lib/kubelet"
   local APISERVER
   local ENDPOINT_AMOUNT
-  if [[ "${LOCAL_ETCD_ONLY}" == "true" ]]; then
-    exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
+  if [[ "${REMOTE_ETCD_IPADDR}" == "${IPADDR}" ]] \
+   || [[ "${REMOTE_K8S_IPADDR}" == "${IPADDR}" ]];then
+    echo "Remote IP address can not be local IP address, exiting..." 1>&2
+    exit 1
+  fi
+
+  if [[ "${EXIT_LOCAL_ETCD_ONLY}" == "true" ]]; then
+    exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${REMOTE_ETCD_IPADDR}"
     exit 0
   fi
-  if [[ "${REMOTE_ETCD}" == "true" ]]; then
-    LOCAL_ETCD="false"
-    exit_etcd "${REMOTE_IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
+  if [[ -n "${REMOTE_ETCD_IPADDR}" ]]; then
+    exit_etcd "${REMOTE_IPADDR}" "${ETCD_CLIENT_PORT}" "${REMOTE_ETCD_IPADDR}"
     exit 0
   fi
   if [[ "${FORCE}" == "true" ]]; then
@@ -305,24 +347,24 @@ function main(){
     docker stop $(docker ps -a | grep -E "k8sup-kubelet" | awk '{print $1}') 1>/dev/null || true
     docker rm -f -v $(docker ps -a | grep -E "k8s_([[:alnum:]]|-)+\.[[:alnum:]]{7,8}_.*_kube-system" | awk '{print $1}') 1>/dev/null || true
     if [[ "${EXIT}" == "true" ]]; then
-      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
+      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${REMOTE_ETCD_IPADDR}"
     fi
   else
     # Default removing
     echo "Stopping k8s containers........." 1>&2
     APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")"
-    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE}" "${APISERVER}"
+    stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${REMOTE_K8S_IPADDR}" "${EXIT}" || true
     ENDPOINT_AMOUNT="$(get_endpoint_amount "${ETCD_CLIENT_PORT}")" || exit 1
     if [[ "${ENDPOINT_AMOUNT}" -gt "1" ]]; then
       # Try to find another apiserver for removing this node from endpoints
       APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")" \
-       && remove_node_from_endpoints "${HYPERKUBE_IMAGE}" "${APISERVER}" "${KUBELET_VARLIB}" || true
+       && remove_node_from_endpoints "${HYPERKUBE_IMAGE}" "${APISERVER}" "${KUBELET_VARLIB}" "${REMOTE_K8S_IPADDR}" || true
     fi
-    if [[ "${STOP_K8S_ONLY}" == "true" ]]; then
+    if [[ "${STOP_K8S_ONLY}" == "true" ]] || [[ -n "${REMOTE_K8S_IPADDR}" ]]; then
       exit 0
     fi
     if [[ "${EXIT}" == "true" ]]; then
-      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${LOCAL_ETCD}"
+      exit_etcd "${IPADDR}" "${ETCD_CLIENT_PORT}" "${REMOTE_ETCD_IPADDR}"
     fi
   fi
 
