Integrate a NTP server as a k8s cluster service.

diff --git a/kube-down b/kube-down
--- a/kube-down
+++ b/kube-down
@@ -1,5 +1,8 @@
 #!/bin/bash
 set -e
+source "$(dirname "$0")/runcom" || { echo 'Can not load the rumcom file, exiting...' >&2 && exit 1 ; }
+
+#---
 
 function remove_node_from_endpoints(){
   local IPPORT_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{1,5\}"
@@ -63,7 +66,7 @@ function get_endpoint_amount(){
   local NODE_LIST="$(curl -m 2 -sf "127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/services/endpoints/default/kubernetes" \
                      | jq -r '.node.value' \
                      | jq -r '.subsets[].addresses[].ip')"
-  [[ -z "${NODE_LIST}" ]] && { echo "Could not connect to etcd server!" 1>&2; return 1; }
+  [[ -z "${NODE_LIST}" ]] && { echo "Could not get API server endpoints from etcd server!" 1>&2; return 1; }
   [[ "${NODE_LIST}" == "null" ]] && { echo "No such any endpoint!" 1>&2; return 1; }
 
   local ENDPOINT_AMOUNT="$(echo "${NODE_LIST}" | wc -l)"
@@ -90,7 +93,7 @@ function find_an_apiserver(){
     local NODE_LIST="$(curl -m 2 -sf "127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/services/endpoints/default/kubernetes" \
                        | jq -r '.node.value' \
                        | jq -r '.subsets[].addresses[].ip')"
-    [[ -z "${NODE_LIST}" ]] && { echo "Could not connect to etcd server!" 1>&2; return 1; }
+    [[ -z "${NODE_LIST}" ]] && { echo "Could not get API server endpoints from etcd server!" 1>&2; return 1; }
 
     for NODE in ${NODE_LIST}; do
       if curl -k -m 2 -s "https://${NODE}:${K8S_PORT}" &>/dev/null; then
@@ -307,7 +310,6 @@ function get_options(){
 }
 
 function main(){
-  source "$(dirname "$0")/runcom"
   get_options "$@"
 
   source "/root/.bashrc"
