Use hostname instead of node IP as k8s node name

diff --git a/kube-down b/kube-down
--- a/kube-down
+++ b/kube-down
@@ -32,6 +32,32 @@ function kube_down_save_log(){
   docker inspect "${CONTAINER_ID}" &>"/etc/kubernetes/logs/${LOGNAME}.json"
 }
 
+function get_node_ip_by_node_name(){
+  local NODE_NAME="$1"
+  local HYPERKUBE_IMAGE="$2"
+  local APIHOST="$(echo "$3" | grep -o "${IPPORT_PATTERN}")"
+  local KUBELET_VARLIB="$4"
+  local APISERVER=""
+  local NODE_IPADDR
+
+  NODE_IPADDR="$(docker run \
+    --net=host \
+    --rm=true \
+    --volume=${KUBELET_VARLIB}/kubeconfig:${KUBELET_VARLIB}/kubeconfig:ro \
+    "${HYPERKUBE_IMAGE}" \
+    /hyperkube kubectl -s "${APISERVER}" \
+      --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
+      get node "${NODE_NAME}" -o json \
+        | jq -r '.status.addresses[0].address')"
+
+  if [[ -n "${NODE_IPADDR}" ]]; then
+    echo "${NODE_IPADDR}"
+  else
+    echo "Error: Could not get node IP address by node name." 1>&2
+    return 1
+  fi
+}
+
 function remove_node_from_endpoints(){
   local IPPORT_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{1,5\}"
   local IPADDR="$1"
@@ -161,24 +187,24 @@ function find_an_apiserver(){
 
 function stop_k8s(){
   local IPPORT_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}:[0-9]\{1,5\}"
-  local IPADDR="$1"
+  local NODE_NAME="$1"
   local ETCD_CLIENT_PORT="$2"
   local KUBELET_VARLIB="$3"
   local HYPERKUBE_IMAGE="$4"
   local APIHOST="$(echo "$5" | grep -o "${IPPORT_PATTERN}")"
-  local REMOTE_K8S_IPADDR="$6"
+  local REMOTE_K8S_NODE_NAME="$6"
   local EXIT="$7"
   local CONTAINER_IDS=""
   local APISERVER=""
 
   # Only for exit remote k8s service
-  if [[ -n "${REMOTE_K8S_IPADDR}" ]]; then
-    IPADDR="${REMOTE_K8S_IPADDR}"
+  if [[ -n "${REMOTE_K8S_NODE_NAME}" ]]; then
+    NODE_NAME="${REMOTE_K8S_NODE_NAME}"
     EXIT="true"
   fi
   if [[ "${APIHOST}" == "127.0.0.1"* ]]; then
     APISERVER="http://${APIHOST}"
-  elif [[ -n "${APIHOST}" ]] && [[ -z "${REMOTE_K8S_IPADDR}" ]]; then
+  elif [[ -n "${APIHOST}" ]] && [[ -z "${REMOTE_K8S_NODE_NAME}" ]]; then
     # Only for exit local k8s service
     iptables -w -t nat -I OUTPUT --dest 10.0.0.1 -p tcp --dport 443 -j DNAT --to-dest "${APIHOST}"
     APISERVER="https://10.0.0.1:443"
@@ -197,7 +223,7 @@ function stop_k8s(){
         "${HYPERKUBE_IMAGE}" \
         /hyperkube kubectl -s "${APISERVER}" \
           --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
-          drain "${IPADDR}" --force --ignore-daemonsets --delete-local-data 2>&1)"; do
+          drain "${NODE_NAME}" --force --ignore-daemonsets --delete-local-data 2>&1)"; do
     [[ "$(echo "${MSG}" | grep "nodes .* not found")" ]] && return 1
     echo "Try again..." 1>&2
     sleep 1
@@ -213,7 +239,7 @@ function stop_k8s(){
       "${HYPERKUBE_IMAGE}" \
       /hyperkube kubectl -s "${APISERVER}" \
         --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
-        delete node "${IPADDR}"
+        delete node "${NODE_NAME}"
 
     # Stop all OSD containers on this node
     CONTAINER_IDS="$(docker ps | grep -E "k8s_ceph-osd-pod.[[:alnum:]]{7,8}_ceph-osd-[[:alnum:]]{5}_ceph" | awk '{print $1}')"
@@ -230,13 +256,13 @@ function stop_k8s(){
             --kubeconfig ${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
             get po --all-namespaces -o wide \
               | grep -v "\<kube-system\>" \
-              | grep "\<${IPADDR}\>" &>/dev/null; do
+              | grep "\<${NODE_NAME}\>" &>/dev/null; do
       sleep 2
     done
   fi
 
   # Only for exit local k8s service
-  if [[ -z "${REMOTE_K8S_IPADDR}" ]]; then
+  if [[ -z "${REMOTE_K8S_NODE_NAME}" ]]; then
     # Remove k8s system pods conf
     echo '{}' | tee /etc/kubernetes/manifests-multi/master-multi.json &>/dev/null
     echo '{}' | tee /etc/kubernetes/manifests-multi/addon-manager-multinode.json &>/dev/null
@@ -272,7 +298,7 @@ function stop_k8s(){
       iptables -w -t nat -D OUTPUT --dest 10.0.0.1 -p tcp --dport 443 -j DNAT --to-dest "${APIHOST}"
     fi
   else
-    echo "K8S node ${IPADDR} has been exited." 1>&2
+    echo "K8S node ${NODE_NAME} has been exited." 1>&2
   fi
 }
 
@@ -306,7 +332,7 @@ Options:
 -f, --force                              Force to kill named k8sup containers
     --exit-local-etcd-only               Exit the local etcd member from cluster
     --exit-remote-etcd=REMOTE_IPADDR     Exit the remote etcd member from cluster
-    --exit-remote-k8s=REMOTE_IPADDR      Exit the remote k8s node from cluster
+    --exit-remote-k8s=REMOTE_NODE_NAME   Exit the remote k8s node from cluster
     --debug                              Enable debug mode
 -h, --help                               This help text
 "
@@ -348,7 +374,7 @@ function get_options(){
               shift 2
               ;;
              --exit-remote-k8s)
-              export EX_REMOTE_K8S_IPADDR="$2"
+              export EX_REMOTE_K8S_NODE_NAME="$2"
               shift 2
               ;;
              --debug)
@@ -378,11 +404,6 @@ function get_options(){
     echo "Need IP address of remote etcd node, exiting..." 1>&2
     exit 1
   fi
-  if [[ -n "${EX_REMOTE_K8S_IPADDR}" ]] \
-   && [[ -z "$(echo "${EX_REMOTE_K8S_IPADDR}" | grep -o "${IPADDR_PATTERN}")" ]]; then
-    echo "Need IP address of remote k8s node, exiting..." 1>&2
-    exit 1
-  fi
 }
 
 function main(){
@@ -407,7 +428,9 @@ function main(){
   local EXIT_LOCAL_ETCD_ONLY="${EX_EXIT_LOCAL_ETCD_ONLY}"
   local START_ETCD_ONLY="${EX_START_ETCD_ONLY}"
   local REMOTE_ETCD_IPADDR="${EX_REMOTE_ETCD_IPADDR}"
-  local REMOTE_K8S_IPADDR="${EX_REMOTE_K8S_IPADDR}"
+  local REMOTE_K8S_NODE_NAME="${EX_REMOTE_K8S_NODE_NAME}"
+  local REMOTE_K8S_IPADDR
+  local NODE_NAME="${EX_NODE_NAME}"
   local FORCE="${EX_FORCE}"
   local KUBELET_VARLIB="/var/lib/kubelet"
   local APISERVER
@@ -453,16 +476,17 @@ function main(){
     # Default removing
     if [[ "${START_ETCD_ONLY}" != "true" ]]; then
       echo "Stopping k8s containers........." 1>&2
-      APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")" || exit 1
-      stop_k8s "${IPADDR}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${REMOTE_K8S_IPADDR}" "${EXIT}" || true
-      cleanup_old_kubeproxy_iptables "${HYPERKUBE_IMAGE}"
-      APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")" \
-        && ENDPOINT_AMOUNT="$(get_endpoint_amount "${HYPERKUBE_IMAGE}" "${KUBELET_VARLIB}" "${APISERVER}")" \
-        || ENDPOINT_AMOUNT="0"
+      APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")"
+      stop_k8s "${NODE_NAME}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${REMOTE_K8S_NODE_NAME}" "${EXIT}" || true
+      ENDPOINT_AMOUNT="$(get_endpoint_amount "${ETCD_CLIENT_PORT}")" || exit 1
       if [[ "${ENDPOINT_AMOUNT}" -gt "1" ]]; then
         # Try to find another apiserver for removing this node from endpoints
-        APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")" \
-         && remove_node_from_endpoints "${IPADDR}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${KUBELET_VARLIB}" "${REMOTE_K8S_IPADDR}" || true
+        if APISERVER="$(find_an_apiserver "${ETCD_CLIENT_PORT}" "${K8S_PORT}" "${K8S_INSECURE_PORT}" "${KUBELET_VARLIB}")"; then
+          if [[ -n "${REMOTE_K8S_NODE_NAME}" ]]; then
+            REMOTE_K8S_IPADDR="$(get_node_ip_by_node_name "${REMOTE_K8S_NODE_NAME}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${KUBELET_VARLIB}")"
+          fi
+          remove_node_from_endpoints "${IPADDR}" "${HYPERKUBE_IMAGE}" "${APISERVER}" "${KUBELET_VARLIB}" "${REMOTE_K8S_IPADDR}" || true
+        fi
       fi
     fi
     if [[ "${STOP_K8S_ONLY}" == "true" ]] || [[ -n "${REMOTE_K8S_IPADDR}" ]]; then
