Fix kube-apiservers use default interface IPs as endpoints

diff --git a/kube-up b/kube-up
--- a/kube-up
+++ b/kube-up
@@ -305,22 +305,6 @@ function update_node_role_label(){
   done
 }
 
-function get_default_iface_ipaddr(){
-  local IPMASK_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,2\}"
-  local GW_IFACE="$(ip route | grep default | awk '{print $5}')"
-  local GW_IPADDR="$(ip addr show dev "${GW_IFACE}" | grep -o "${IPMASK_PATTERN}" | cut -d '/' -f 1)"
-
-  echo "${GW_IPADDR}"
-}
-
-function mark_default_iface_ipaddr(){
-  local IPADDR="$1"
-  local ETCD_CLIENT_PORT="$2"
-  local GW_IPADDR="$(get_default_iface_ipaddr)"
-
-  curl -sf "http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/k8sup/cluster/default-iface-ipaddr/${IPADDR}" -XPUT -d value="${GW_IPADDR}" 1>/dev/null
-}
-
 function show_usage(){
   USAGE="Usage: ${0##*/} [options...]
 Options:
@@ -343,7 +327,7 @@ Options:
 function get_options(){
   local PROGNAME="${0##*/}"
   local SHORTOPTS="i:wa:v:r:h"
-  local LONGOPTS="ip:,apiserver-port:,etcd-port:,creator,worker,version:,registry:,forced-worker,reset-labels,enable-keystone,help"
+  local LONGOPTS="ip-cidr:,apiserver-port:,etcd-port:,creator,worker,version:,registry:,forced-worker,reset-labels,enable-keystone,help"
   local PARSED_OPTIONS=""
 
   PARSED_OPTIONS="$(getopt -o "${SHORTOPTS}" --long "${LONGOPTS}" -n "${PROGNAME}" -- "$@")" || exit 1
@@ -352,8 +336,8 @@ function get_options(){
   # extract options and their arguments into variables.
   while true ; do
       case "$1" in
-          -i|--ip)
-              export EX_IPADDR="$2"
+          -i|--ip-cidr)
+              export EX_IPCIDR="$2"
               shift 2
               ;;
           -a|--apiserver-port)
@@ -410,10 +394,10 @@ function get_options(){
       esac
   done
 
-
-  if [[ -z "${EX_IPADDR}" ]] || \
-   [[ -z "$(ip addr | sed -nr "s/.*inet ([^ ]+)\/.*/\1/p" | grep -w "${EX_IPADDR}")" ]]; then
-    echo "IP address error, exiting..." 1>&2
+  local IPCIDR_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,2\}"
+  if [[ -z "$(echo "${EX_IPCIDR}" | grep -o "${IPCIDR_PATTERN}")" ]] || \
+   [[ -z "$(ip addr | sed -nr "s/.*inet ([^ ]+) .*/\1/p" | grep -w "${EX_IPCIDR}")" ]]; then
+    echo "IP/CIDR error, exiting..." 1>&2
     exit 1
   fi
 
@@ -495,7 +479,7 @@ function get_API_Servers(){
 
 function main(){
   get_options "$@"
-  local IPADDR="${EX_IPADDR}" && unset EX_IPADDR
+  local IPCIDR="${EX_IPCIDR}" && unset EX_IPCIDR
   local WORKER="${EX_WORKER}" && unset EX_WORKER
   local FORCED_WORKER="${EX_FORCED_WORKER}" && unset EX_FORCED_WORKER
   local APISERVER_PORT="${EX_APISERVER_PORT}" && unset EX_APISERVER_PORT
@@ -503,6 +487,7 @@ function main(){
   local RESET_LABELS="${EX_RESET_LABELS}" && unset EX_RESET_LABELS
   local ENABLE_KEYSTONE="${EX_ENABLE_KEYSTONE}" && unset EX_ENABLE_KEYSTONE
   local CREATOR="${EX_CREATOR}" && unset EX_CREATOR
+  local IPADDR="$(echo "${IPCIDR}" | cut -d '/' -f 1)"
   local ETCD_PROXY=""
   local APIHOST=""
   local APISERVER=""
@@ -581,6 +566,7 @@ function main(){
   sed -i "s|\bNTPSERVER_REGISTRY\b|${NTPSERVER_REGISTRY}|g" "${KUBE_ADDONS_CONF_PATH/}"/ntp-server/*.yaml
   sed -i "s|\bK8SUP_NTPSERVER_VERSION\b|${K8SUP_NTPSERVER_VERSION}|g" "${KUBE_ADDONS_CONF_PATH/}"/ntp-server/*.yaml
   sed -i "s|\"--v=[0-9]\"|\"--v=${K8S_DEBUG_LEVEL}\"|g" "${KUBE_CONF_PATH}"/master-multi.json "${KUBE_ADDONS_CONF_PATH}"/kube-proxy.yaml
+  sed -i "s|\bNODE_IPADDR\b|${IPADDR}|g" "${KUBE_CONF_PATH}"/master-multi.json
 
   # Replace strings in all json and yaml files in sub-directories
   [[ "${REGISTRY}" == "gcr.io/google_containers" ]] && local KUBERNETES_REGISTRY="kubernetes" || local KUBERNETES_REGISTRY="${REGISTRY}"
@@ -669,13 +655,21 @@ function main(){
            | grep 10.0.0.1/32 \
            | sed "s/^-A/-D/g" \
            | sed -n 's|\(^.*$\)|iptables -w -t nat \1|p')
-  # Add new a rule
+  # Remove old route rules
+  if ip route | grep -w "^10.0.0.1 dev" 1>/dev/null; then
+    ip route delete "10.0.0.1"
+  fi
+  # Add a new route rule
   iptables -w -t nat -I OUTPUT --dest 10.0.0.1 -p tcp --dport 443 \
     -m comment --comment "k8sup" -j DNAT --to-dest "${APIHOST}"
 
   # Make sure that this host will use the right interface while accessing API server
-  local GW_IFACE="$(ip route | grep default | awk '{print $5}')"
-  ip route add 10.0.0.1/32 dev "${GW_IFACE}" &>/dev/null || true
+  local IFACE="$(ip addr | grep -B2 "inet ${IPCIDR}" | sed -n "s|^[0-9]\+: \(.*\): .*|\1|p" | cut -d '@' -f 1)"
+  if [[ -z "${IFACE}" ]] || ! ip addr show "${IFACE}" &>/dev/null; then
+    echo "Could not get network interface which use '${IPCIDR}', exiting..." 1>&2
+    exit 1
+  fi
+  ip route add "10.0.0.1/32" dev "${IFACE}" &>/dev/null || true
 
   echo "Running Kubernetes ..."
   docker run \
@@ -705,6 +699,7 @@ function main(){
           --require-kubeconfig=true \
           --kubeconfig=${KUBELET_VARLIB}/kubeconfig/kubeconfig.yaml \
           --v="${K8S_DEBUG_LEVEL}" \
+          --node-ip="${IPADDR}" \
           --address=0.0.0.0 \
           --enable-server \
           --hostname-override="${IPADDR}" \
@@ -730,8 +725,6 @@ function main(){
 
   set_node_schedulable "${IPADDR}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE_NAME}"
   update_node_role_label "${IPADDR}" "${KUBELET_VARLIB}" "${HYPERKUBE_IMAGE_NAME}" "${WORKER}"
-
-  mark_default_iface_ipaddr "${IPADDR}" "${ETCD_CLIENT_PORT}"
 
   # If NTP client is not found then start a NTP client
   if ps aux | grep -v grep | grep -wE "systemd-timesyncd|ntpd" &>/dev/null; then
