Fix could not deploy as worker node

diff --git a/kube-up b/kube-up
--- a/kube-up
+++ b/kube-up
@@ -469,24 +469,40 @@ function get_API_Servers(){
   local APISERVER=""
   local APIHOST=""
   local KUBE_NODE_LIST=""
+  local IPADDR_PATTERN="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
   local CERTS_DIR="${KUBELET_VARLIB}/kubeconfig"
   local CERT_OPTS="--cert ${CERTS_DIR}/kubecfg.crt \
                    --key ${CERTS_DIR}/kubecfg.key \
                    --cacert ${CERTS_DIR}/ca.crt"
 
-  # Wait for any apiserver started
-  until [[ -n "${KUBE_NODE_LIST}" ]]; do
-    KUBE_NODE_LIST="$(curl -m 2 -sf "127.0.0.1:${ETCD_CLIENT_PORT}/v2/keys/registry/services/endpoints/default/kubernetes" \
-                       | jq -r '.node.value' \
-                       | jq -r '.subsets[].addresses[].ip' 2>/dev/null)" || true
-    sleep 1
-  done
+  if [[ ! -f "${CERTS_DIR}/kubecfg.crt" ]] \
+    || [[ ! -f "${CERTS_DIR}/kubecfg.key" ]] \
+    || [[ ! -f "${CERTS_DIR}/ca.crt" ]] \
+    || [[ ! -f "${CERTS_DIR}/kubeconfig.yaml" ]]; then
+   echo "Error, no such cert files in ${CERTS_DIR} or kubeconfig file in ${KUBELET_VARLIB}!" 1>&2
+   return 1
+  fi
 
-  for KUBE_NODE in ${KUBE_NODE_LIST}; do
-    APISERVER="https://${KUBE_NODE}:${APISERVER_PORT}"
-    if curl ${CERT_OPTS} -s -k -m 2 "${APISERVER}/healthz" &>/dev/null; then
-      APISERVERS="${APISERVERS}","${APISERVER}"
-    fi
+  # Wait for any apiserver started
+  until [[ -n "${APISERVERS}" ]]; do
+    # Get apiserver list
+    until [[ -n "${KUBE_NODE_LIST}" ]]; do
+      KUBE_NODE_LIST="$(curl -sf --retry 10 "http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members" \
+        | jq -r ".members[].clientURLs[0]" \
+        | grep -v 'null' \
+        | grep -o "${IPADDR_PATTERN}")"
+
+      sleep 1
+    done
+
+    # Check accessibilities of apiservers
+    for KUBE_NODE in ${KUBE_NODE_LIST}; do
+      APISERVER="https://${KUBE_NODE}:${APISERVER_PORT}"
+      if curl ${CERT_OPTS} -s -k -m 2 "${APISERVER}/healthz" &>/dev/null; then
+        APISERVERS="${APISERVERS}","${APISERVER}"
+      fi
+    done
+    [[ -z "${APISERVERS}" ]] && sleep 1
   done
 
   APISERVERS="$(echo "${APISERVERS}" | cut -c 2-)"
@@ -537,10 +553,6 @@ function main(){
 
   # Reset node labels and exit
   if [[ "${RESET_LABELS}" == "true" ]]; then
-    APISERVERS="$(get_API_Servers "${APISERVER_PORT}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}")" \
-                  || { echo "No such API servers, exiting..." 1>&2; exit 1; }
-    APISERVER="$(echo "${APISERVERS}" | cut -d ',' -f 1)"
-
     local MEMBER_LIST="$(curl -s http://127.0.0.1:${ETCD_CLIENT_PORT}/v2/members)"
     if [[ "${MEMBER_LIST}" == *"${IPADDR}:${ETCD_CLIENT_PORT}"* ]]; then
       WORKER="false"
@@ -649,8 +661,8 @@ function main(){
     APIHOST="$(get_API_Servers "${APISERVER_PORT}" "${ETCD_CLIENT_PORT}" "${KUBELET_VARLIB}" | cut -d ',' -f 1)"
     APIHOST="${APIHOST:8}"
     [[ -z "${APIHOST}" ]] && { echo "No such API servers, exiting..." 1>&2; exit 1; }
-    rm "${KUBE_CONF_PATH}/master-multi.json"
-    rm "${KUBE_CONF_PATH}/addon-manager-multinode.json"
+    rm -f "${KUBE_CONF_PATH}/master-multi.json"
+    rm -f "${KUBE_CONF_PATH}/addon-manager-multinode.json"
   fi
 
   until ! docker ps | grep -w 'k8sup-kubelet'; do
@@ -661,7 +673,9 @@ function main(){
   local RBD_PATHS
   if RBD_PATHS=($(rbd_env_detector)); then
     local RBD_OPTIONS_KUBELET="$(make_rbd_docker_option "${RBD_PATHS[@]}")"
-    update_master_multi_rbd_mount "${RBD_PATHS[@]}" "${KUBE_CONF_PATH}/master-multi.json"
+    if [[ "${WORKER}" == "false" ]]; then
+      update_master_multi_rbd_mount "${RBD_PATHS[@]}" "${KUBE_CONF_PATH}/master-multi.json"
+    fi
   fi
 
   keystone_operation "${ENABLE_KEYSTONE}" "${KEYSTONE_CLUSTER_IP}" \
