If rbd command is not found on host, make a dummy and mount into k8s components, then let others to replace it.

diff --git a/kube-up b/kube-up
--- a/kube-up
+++ b/kube-up
@@ -16,11 +16,76 @@ function set_role_labels(){
   echo "${ROLE_LABELS}"
 }
 
+function get_container_dirpath_from_host_volumes(){
+  local HOST_DIR_PATH="$1"
+  local VOLUMES="$2"
+  local EXCLUDE_DIR_OPTION
+  local VOL_SRC
+  local VOL_DEST
+  local CONTAINER_DIR_PATH
+  local IFS
+  local IDX
+  local DROP
+  local AVAILABLE_VOLUME
+  local VOL
+  local DIR
+  local PATH_ADD
+  local TEST_FILE
+
+  # Find the volume that include the expected host path
+  [[ -z "${HOST_DIR_PATH}" ]] && return 1
+  [[ -z "${VOLUMES}" ]] && VOLUMES="$(docker inspect k8sup | jq -r '.[0].HostConfig.Binds[]' 2>/dev/null | cut -d ':' -f 1-2)"
+  for VOL in ${VOLUMES}; do
+    VOL_SRC="$(echo "${VOL}" | cut -d ':' -f 1 | sed "s|/$||g")"
+    VOL_DEST="$(echo "${VOL}" | cut -d ':' -f 2 | sed "s|/$||g")"
+
+    [[ "${VOL_SRC}" == "/" ]] && { echo "${VOL_DEST}${HOST_DIR_PATH}" | sed "s|//|/|g" | sed "s|/$||g"; return 0; }
+
+    DROP="false"
+    IDX="1"
+    IFS='/' read -ra DIRS <<< ${VOL_SRC}
+    for DIR in "${DIRS[@]}"; do
+      if [[ "${DIR}" != "$(echo "${HOST_DIR_PATH}" | cut -d '/' -f "${IDX}")" ]]; then
+        DROP="true"
+        break
+      fi
+      ((IDX++))
+    done
+    # Check if it is read-only
+    if [[ "${DROP}" == "false" ]] \
+       && TEST_FILE="$(uuidgen -r)" \
+       && touch "${VOL_DEST}/${TEST_FILE}" 2>/dev/null; then
+      rm "${VOL_DEST}/${TEST_FILE}"
+      AVAILABLE_VOLUME="${VOL}"
+      break
+    fi
+  done
+
+  # Get the container path that equal the expected host path
+  if [[ -n "${AVAILABLE_VOLUME}" ]]; then
+    VOL_SRC="$(echo "${AVAILABLE_VOLUME}" | cut -d ':' -f 1 | sed "s|/$||g")"
+    VOL_DEST="$(echo "${AVAILABLE_VOLUME}" | cut -d ':' -f 2 | sed "s|/$||g")"
+    IDX="1"
+    IFS='/' read -ra DIRS <<< "${HOST_DIR_PATH}"
+    for DIR in "${DIRS[@]}"; do
+      if [[ "${DIR}" != "$(echo "${VOL_SRC}" | cut -d '/' -f "${IDX}")" ]]; then
+        PATH_ADD="${PATH_ADD}/${DIR}"
+      fi
+      ((IDX++))
+    done
+    echo "$(echo "${VOL_DEST}/${PATH_ADD}" | sed "s|//|/|g" | sed "s|/$||g")"
+    return 0
+  fi
+
+  return 1
+}
+
 function get_filepath_from_volumes(){
   local FILENAME="$1"
   local VOLUMES="$2"
   local EXECUTABLE="$3"
   local EXCLUDE_DIR_OPTION
+  local VOL
   local VOL_SRC
   local VOL_DEST
   local FILEPATH
@@ -32,7 +97,7 @@ function get_filepath_from_volumes(){
     VOL_SRC="$(echo "${VOL}" | cut -d ':' -f 1)"
     VOL_DEST="$(echo "${VOL}" | cut -d ':' -f 2)"
     [[ -d "${VOL_DEST}/var/lib/docker" ]] && EXCLUDE_DIR_OPTION="-not -path */var/lib/docker/*" || EXCLUDE_DIR_OPTION=""
-    FILEPATH="$(find "${VOL_DEST}" ${EXECUTABLE_OPTION} -type f ${EXCLUDE_DIR_OPTION} \
+    FILEPATH="$(find "${VOL_DEST}" ${EXECUTABLE_OPTION} -type f ${EXCLUDE_DIR_OPTION} ! -size 0 \
                 -name "${FILENAME}" -o -type l -name "${FILENAME}" 2>/dev/null | head -n 1)"
     if [[ -n "${FILEPATH}" ]]; then
       if [[ -f "${VOL_DEST}" ]]; then
@@ -101,14 +166,30 @@ function rbd_env_detector(){
   local MODPROBE_CMD_PATH
   local DOCKER_CMD_PATH
   local VOLUMES="$(docker inspect k8sup | jq -r '.[0].HostConfig.Binds[]' 2>/dev/null | cut -d ':' -f 1-2)"
+  local DEFAULT_RBD_CMD_HOST_PATH="/opt/bin"
+  local RBD_CMD_CONTAINER_PATH
 
   [[ -n "$(echo "${VOLUMES}" | grep "/usr/lib")" ]] \
     && [[ -n "$(echo "${VOLUMES}" | grep "/bin")" ]] \
-    && RBD_CMD_PATH="$(get_filepath_from_volumes "rbd" "${VOLUMES}" "true")" \
     && RBD_KO_PATH="$(get_filepath_from_volumes "rbd.ko" "${VOLUMES}")" \
     && MODPROBE_CMD_PATH="$(get_filepath_from_volumes "modprobe" "${VOLUMES}" "true")" \
     && DOCKER_CMD_PATH="$(get_filepath_from_volumes "docker" "$(echo "${VOLUMES}" | grep "/bin")" "true")" \
     || { echo "RBD mounting is not available on this host." 1>&2 && return 1; }
+
+    if ! RBD_CMD_PATH="$(get_filepath_from_volumes "rbd" "${VOLUMES}" "true")"; then
+      # If the existing rbd command is not found, touch the empty executable file to the default rbd command host path
+      # and mount into k8s components then let other container to replace it.
+      if RBD_CMD_CONTAINER_PATH="$(get_container_dirpath_from_host_volumes "${DEFAULT_RBD_CMD_HOST_PATH}" "${VOLUMES}")/rbd"; then
+        touch "${RBD_CMD_CONTAINER_PATH}" 2>/dev/null \
+          || { echo "Could not write \"${DEFAULT_RBD_CMD_HOST_PATH}\", RBD mounting is not available on this host."; return 1; }
+        chmod +x "${RBD_CMD_CONTAINER_PATH}"
+        echo "Need somebody to copy RBD command to the host path: \"${DEFAULT_RBD_CMD_HOST_PATH}/rbd\" who needs to use RBD service." 1>&2
+        RBD_CMD_PATH="${DEFAULT_RBD_CMD_HOST_PATH}/rbd"
+      else
+        echo "Could not find any writable volume mount from the host path: \"${DEFAULT_RBD_CMD_HOST_PATH}\", RBD mounting is not available on this host." 1>&2
+        return 1
+      fi
+    fi
 
   echo "RBD mounting is available on this host." 1>&2
   echo "${RBD_CMD_PATH}" "${RBD_KO_PATH}" "${MODPROBE_CMD_PATH}" "${DOCKER_CMD_PATH}"
